# Generated by Django 4.1.13 on 2023-12-05 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugadores',
            old_name='perteneceid',
            new_name='pertenece_id',
        ),
    ]
